version: '3.8'

networks:
  inception_net:

volumes:
  mariadb_volume:
    driver_opts:
      type: none
      o: bind
      device: /home/gjupy/data/mariadb
  wordpress_volume:
    driver_opts:
      type: none
      o: bind
      device: /home/gjupy/data/wordpress

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    ports:
      - '3306:3306'
    networks:
      - inception_net
    volumes:
      - mariadb_volume:/var/lib/mysql
    env_file: .env
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    ports:
      - '9000:9000'
    networks:
      - inception_net
    volumes:
      - wordpress_volume:/var/www/html/wordpress
    env_file: .env
    depends_on:
      - mariadb
    restart: always

  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    networks:
      - inception_net
    volumes:
      - wordpress_volume:/var/www/html/wordpress
    depends_on:
      - wordpress
      - mariadb
    restart: always